export const GO_HOME = 'GO_HOME';
export const GO_ABOUT = 'GO_ABOUT';
export const GO_SERVICES = 'GO_SERVICES';
export const GO_PROJECTS = 'GO_PROJECTS';
export const GO_CONTACT = 'GO_CONTACT';

export const SEND_MAIL_START = 'SEND_MAIL_START';
export const SEND_MAIL_SUCCESS = 'SEND_MAIL_SUCCESS';
export const SEND_MAIL_FAIL = 'SEND_MAIL_FAIL';
export const SEND_MAIL_RESET = 'SEND_MAIL_RESET';

export const SCREEN_CLOSE_SIDE_DRAWER = 'SCREEN_CLOSE_SIDE_DRAWER';
export const SCREEN_OPEN_SIDE_DRAWER = 'SCREEN_OPEN_SIDE_DRAWER';